return {
  -- {
  --   "supermaven-inc/supermaven-nvim",
  --   -- lazy = false,
  --   event = { "BufReadPre", "BufNewFile" },
  --   opts = {
  --   keymaps = {
  --     accept_suggestion = "<Tab>",
  --     clear_suggestion = "<C-]",
  --     accept_word = "<C-y>",
  --   },
  --   -- color = {
  --   --   suggestion_color = "#ffffff",
  --   --   cterm = 244,
  --   -- },
  --   disable_keymaps = false,
  --   log_level = "info",
  --   dsable_inline_completion = false,
  --   },
  -- },
}
